#!/bin/bash
-rw-r--r-- 1 root root 16 Oct  7 06:35 0-current_working_directory
-rw-r--r-- 1 root root 16 Oct  7 13:04 1-listit
-rw-r--r-- 1 root root 15 Oct  7 13:22 2-bring_me_home
-rw-r--r-- 1 root root 16 Oct  7 13:27 3-listfiles
-rw-r--r-- 1 root root 26 Oct  7 12:55 README.md
